[features]
seeds = false
skip-lint = false

[programs.localnet]
custom_clock = "CLockX54wfiQwQoRGcMAxitSPKdNcSRousbcHEJoecou"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[test.validator]
limit_ledger_size = "1000000"
