[package]
name = "counter"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
name = "counter"

[dependencies]
advance = { workspace = true }
borsh = { workspace = true }
bytemuck = { workspace = true }
solana-program = "~1.18"
star_frame = { workspace = true }

[dev-dependencies]
solana-client = "~1.18"
solana-program-test = "~1.18"
solana-sdk = { version = "~1.18" }
solana-transaction-status = "~1.18"
tokio = "1.39.1"